/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TnagCollaborationRouteImport } from './routes/tnag-collaboration'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TnagCollaborationRoute = TnagCollaborationRouteImport.update({
  id: '/tnag-collaboration',
  path: '/tnag-collaboration',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tnag-collaboration': typeof TnagCollaborationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tnag-collaboration': typeof TnagCollaborationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tnag-collaboration': typeof TnagCollaborationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tnag-collaboration'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tnag-collaboration'
  id: '__root__' | '/' | '/tnag-collaboration'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TnagCollaborationRoute: typeof TnagCollaborationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tnag-collaboration': {
      id: '/tnag-collaboration'
      path: '/tnag-collaboration'
      fullPath: '/tnag-collaboration'
      preLoaderRoute: typeof TnagCollaborationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TnagCollaborationRoute: TnagCollaborationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
